// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function LoadJSONFile():Promise<string>;

export function PrintAppDataLocal():Promise<void>;

export function SaveJSONFile(arg1:string):Promise<void>;

export function SaveWeightedClass(arg1:main.WeightedClass):Promise<void>;
