// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadJSONFile() {
  return window['go']['main']['App']['LoadJSONFile']();
}

export function PrintAppDataLocal() {
  return window['go']['main']['App']['PrintAppDataLocal']();
}

export function SaveJSONFile(arg1) {
  return window['go']['main']['App']['SaveJSONFile'](arg1);
}

export function SaveWeightedClass(arg1) {
  return window['go']['main']['App']['SaveWeightedClass'](arg1);
}
